[project]
name = "canagon"
version = "0.1.0"
description = "Official canagon package - see canagon.com"
readme = "README.md"
requires-python = ">=3.8"

[project.urls]
Homepage = "https://www.canagon.com"
